// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBsWAUil-jloVCdkMekev42GvtVPgdk1Y',
    appId: '1:1054650478078:android:576345a5de2e631bbbe4af',
    messagingSenderId: '1054650478078',
    projectId: 'zoom-clone-2638c',
    storageBucket: 'zoom-clone-2638c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzEz9d8uk8QZLNtpvascw-oy-VlrxZSC4',
    appId: '1:1054650478078:ios:3e4b2ebe335d0572bbe4af',
    messagingSenderId: '1054650478078',
    projectId: 'zoom-clone-2638c',
    storageBucket: 'zoom-clone-2638c.appspot.com',
    androidClientId: '1054650478078-urg7brpubjbh63prmets472ghi11vagj.apps.googleusercontent.com',
    iosClientId: '1054650478078-6m74qp8shc35drlrso5v0urga3ufi3g0.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomClone',
  );
}
